default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  <% if ENV["DB_HOST"] %>
  host: <%= ENV["DB_HOST"] %>
  username: postgres
  password: postgres
  <% end %>

development:
  <<: *default
  database: willow_page_development

test:
  <<: *default
  database: willow_page_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    url: <%= ENV["CACHE_DATABASE_URL"] %>
    database: willow_page_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    URL: <%= ENV["QUEUE_DATABASE_URL"] %>
    database: willow_page_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    url: <%= ENV["CABLE_DATABASE_URL"] %>
    database: willow_page_production_cable
    migrations_paths: db/cable_migrate
