// Code generated by heroicons generator; DO NOT EDIT.
package icons

import (
	"embed"
	"fmt"
	"html/template"
	"strings"

	"github.com/patrickward/go-heroicons"
)

const IconCustom = "custom"

//go:embed icons/*.svg custom/*.svg
var iconFS embed.FS

// FailOnError determines whether to use a generic missing icon when an icon is not found
var FailOnError = true 

// IconType represents the different types of Heroicons
type IconType string

const (
	IconOutline IconType = "outline" // 24px outline icons
	IconSolid   IconType = "solid"   // 24px solid icons
	IconMini    IconType = "mini"    // 20px solid icons
	IconMicro   IconType = "micro"   // 16px solid icons
)

var iconPaths = map[string]string{
	"mini/arrow-left-start-on-rectangle": "mini_arrow-left-start-on-rectangle.svg",
	"mini/check": "mini_check.svg",
	"mini/lock-closed": "mini_lock-closed.svg",
	"mini/plus": "mini_plus.svg",
	"outline/arrow-top-right-on-square": "outline_arrow-top-right-on-square.svg",
	"outline/bars-3": "outline_bars-3.svg",
	"outline/check": "outline_check.svg",
	"outline/cog-6-tooth": "outline_cog-6-tooth.svg",
	"outline/document": "outline_document.svg",
	"outline/user-circle": "outline_user-circle.svg",
}

// RenderIcon returns the SVG content for the specified icon with added classes
func RenderIcon(name string, iconType heroicons.IconType, class string) (template.HTML, error) {
	svg, err := getIcon(name, iconType)
	if err != nil {
		return "", err
	}

	// If class is provided, insert it into the SVG
	if class != "" {
		if strings.Contains(svg, "class=\"") {
			svg = strings.Replace(svg, "class=\"", fmt.Sprintf("class=\"%s ", class), 1)
		} else {
			svg = strings.Replace(svg, "<svg ", fmt.Sprintf("<svg class=\"%s\" ", class), 1)
		}
	}

	return template.HTML(svg), nil
}

func getMissingIcon() string {
	content, err := iconFS.ReadFile("custom/missing.svg")
	if err != nil {
		return ""
	}
	return string(content)
}

func getIcon(name string, iconType heroicons.IconType) (string, error) {
	if iconType == IconCustom {
		// Look in custom directory 
		content, err := iconFS.ReadFile(fmt.Sprintf("custom/%s.svg", name))
		if err == nil {
			return string(content), nil
		} 
	} else {
		key := fmt.Sprintf("%s/%s", iconType, name)
		if filename, ok := iconPaths[key]; ok {
	        content, err := iconFS.ReadFile(fmt.Sprintf("icons/%s", filename))	
			if err == nil {
				return string(content), nil
			}
		}
	}

	// Fall back to missing icon if not found
	if FailOnError {
		return "", fmt.Errorf("icon not found: %s/%s", iconType, name)
	}

	return getMissingIcon(), nil
}

func getIconOLD(name string, iconType heroicons.IconType) (string, error) {
	key := fmt.Sprintf("%s/%s", iconType, name)
	filename, ok := iconPaths[key]
	if !ok {
		if FailOnError {
			return "", fmt.Errorf("icon not found: %s", key)
		}
		return getMissingIcon(), nil
	}

	filename = fmt.Sprintf("icons/%s", filename)
	content, err := iconFS.ReadFile(filename)
	if err != nil {
		if FailOnError {
			return "", fmt.Errorf("failed to read icon %s: %w", filename, err)
		}
		return getMissingIcon(), nil
	}

	return string(content), nil
}