name: Ruby Gem

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Run tests
        run: rake test
      - name: Build gem
        run: gem build *.gemspec
      - name: Publish to GPR
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
        env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.GH_GEM_HOST_TOKEN}}"
          OWNER: ${{ github.repository_owner }}
      - name: Debug Git State
        run: |
          git status
          git diff
          git ls-files --others --exclude-standard
      - name: Publish to RubyGems
        uses: rubygems/release-gem@v1
